### PR TITLE
[master] Update media codecs profiles from stock

### PR DESCRIPTION
**Pull request by sjllls**
Triple-cameras on pdx201 crashed because of lacking media codecs.

I guess nile has the same issue, you could try it.

Key info:
```
com.android.camera.CameraActivity}: java.lang.IllegalArgumentException: Could not find supported video qualities.
...
11-14 14:43:19.707  3304  3338 D CCodec  : allocate(c2.android.vorbis.decoder)
11-14 14:43:19.713  3304  3338 I Codec2Client: Available Codec2 services: "software"
11-14 14:43:19.713  3304  3338 I Codec2Client: Creating a Codec2 client to service "software"
11-14 14:43:19.715  3304  3338 I Codec2Client: Client to Codec2 service "software" created
11-14 14:43:19.731  3304  3338 I CCodecConfig: query failed after returning 7 values (BAD_INDEX)
11-14 14:43:19.731  3304  3338 D CCodecConfig: c2 config diff is Dict {
11-14 14:43:19.731  3304  3338 D CCodecConfig:   c2::u32 coded.bitrate.value = 64000
11-14 14:43:19.731  3304  3338 D CCodecConfig:   c2::u32 input.buffers.max-size.value = 32768
11-14 14:43:19.731  3304  3338 D CCodecConfig:   c2::u32 input.delay.value = 0
11-14 14:43:19.731  3304  3338 D CCodecConfig:   string input.media-type.value = "audio/vorbis"
11-14 14:43:19.731  3304  3338 D CCodecConfig:   string output.media-type.value = "audio/raw"
11-14 14:43:19.731  3304  3338 D CCodecConfig:   c2::u32 raw.channel-count.value = 1
11-14 14:43:19.731  3304  3338 D CCodecConfig:   c2::u32 raw.sample-rate.value = 48000
11-14 14:43:19.731  3304  3338 D CCodecConfig: }
11-14 14:43:19.732  3304  3338 D CCodecConfig: no c2 equivalents for durationUs
11-14 14:43:19.732  3304  3338 D CCodecConfig: no c2 equivalents for csd-1
11-14 14:43:19.732  3304  3338 D CCodecConfig: no c2 equivalents for track-id
11-14 14:43:19.732  3304  3338 D CCodecConfig: no c2 equivalents for channel-mask
11-14 14:43:19.733  3304  3338 W Codec2Client: query -- param skipped: index = 1107298332.
11-14 14:43:19.734  3304  3338 D CCodec  : setup formats input: AMessage(what = 0x00000000) = {
11-14 14:43:19.734  3304  3338 D CCodec  :   int32_t channel-count = 1
11-14 14:43:19.734  3304  3338 D CCodec  :   int32_t max-input-size = 32768
11-14 14:43:19.734  3304  3338 D CCodec  :   string mime = "audio/vorbis"
11-14 14:43:19.734  3304  3338 D CCodec  :   int32_t sample-rate = 48000
11-14 14:43:19.734  3304  3338 D CCodec  : } and output: AMessage(what = 0x00000000) = {
11-14 14:43:19.734  3304  3338 D CCodec  :   int32_t channel-count = 1
11-14 14:43:19.734  3304  3338 D CCodec  :   string mime = "audio/raw"
11-14 14:43:19.734  3304  3338 D CCodec  :   int32_t sample-rate = 48000
11-14 14:43:19.734  3304  3338 D CCodec  :   int32_t channel-mask = 1
11-14 14:43:19.734  3304  3338 D CCodec  : }
11-14 14:43:19.735  3304  3338 W Codec2Client: query -- param skipped: index = 1342179345.
11-14 14:43:19.735  3304  3338 W Codec2Client: query -- param skipped: index = 2415921170.
11-14 14:43:19.737  3304  3338 D CCodecBufferChannel: [c2.android.vorbis.decoder#876] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
```

### CODE REVIEW

**Comment by sjllls** [comment]
https://github.com/sonyxperiadev/device-sony-pdx201/pull/15
Screenshot_20201115-020228
Screenshot_20201115-023637

**Comment by Haxk20** [comment]
Im guessing the new file comes from stock ?

**Comment by sjllls** [comment]
> Im guessing the new file comes from stock ?

Yup, I described it in commit detail info. :P

**Comment by MarijnS95** [comment]
> Key info:
> 
> ```
> com.android.camera.CameraActivity}: java.lang.IllegalArgumentException: Could not find supported video qualities.
> ...
> 11-14 14:43:19.707  3304  3338 D CCodec  : allocate(c2.android.vorbis.decoder)
> ```

Pretty certain that key info is the stacktrace around `Could not find supported video qualities`  as posted in https://github.com/sonyxperiadev/device-sony-pdx201/pull/15#issuecomment-701328121. The codec info printed here (not even an error) here is for _audio_, probably to play some system sound when the AOSP camera app is opened.

Other than that this indeed solves the AOSP camera crash, thanks! Now we can have all three cameras again :partying_face: 

However, with this and https://github.com/sonyxperiadev/device-sony-pdx201/pull/15 I can't switch to the front camera in AOSP cam: it switches back to the main rear shooter. ~When switching to video mode, it uses the zoom lens~ EDIT: Never mind, it's simply picking another resolution that made it appear zoomed in. The zoom lens gets way closer. @Haxk20 this is likely the same ID mismatch as we had on Mermaid? Front camera is ID 2 here instead of 1.

> Yup, I described it in commit detail info. :P

Can you put it in the _commit_ title instead?

Also FYI we're using a rebasing approach to Q and R branches. If something applies to both (this commit), file a PR against Q and ask Alin to rebase `master` (for R) on top of it. That way we keep these branches from diverging with duplicate commits.

**Comment by Haxk20** [comment]
Yup marijn. I will swap them after work.

**Comment by sjllls** [comment]
> > Key info:
> > ```
> > com.android.camera.CameraActivity}: java.lang.IllegalArgumentException: Could not find supported video qualities.
> > ...
> > 11-14 14:43:19.707  3304  3338 D CCodec  : allocate(c2.android.vorbis.decoder)
...
> Can you put it in the _commit_ title instead?
> 
> Also FYI we're using a rebasing approach to Q and R branches. If something applies to both (this commit), file a PR against Q and ask Alin to rebase `master` (for R) on top of it. That way we keep these branches from diverging with duplicate commits.

No problem! Thanks for infomation!

**Comment by pablomh** [comment]
Is this waiting to be submitted to `R` and be rebased later to `master` or is there any other issue?

**Comment by jerpelea** [comment]
cherrypicked

**Pull request closed without merging**
