### PR TITLE
platform: Move several vars into platform.mk

### PR DESCRIPTION
**Pull request by Haxk20**
Defining these variables earlier means we can make use of
them in `$(inherit)`-ed lowercase makefiles.

Also, move the include of common.mk to the end of the file,
so that common.mk can make use of the variables defined
above.

### CODE REVIEW

**Comment by pablomh** [comment]
Hi @Haxk20, would you mind rebasing against q-mr1 and PR it as well?

**Comment by MarijnS95** [comment]
Would you rather change the target branch to `q-mr1` (and for any other PR that happens to be filed against `master`)? (Click the <edit> button right of the title, then you'll be able to do so).

Master will be rebased on q-mr1 every once in a while so that we're always up-to-date while keeping linear history.

**Comment by MarijnS95** [comment]
Now that I think of it, even though this PR is well applicable to Q didn't we end up deciding to pull this in during the R release window?

**Comment by Haxk20** [comment]
> Hi @Haxk20, would you mind rebasing against q-mr1 and PR it as well?

Those are not meant for Q. Those were specifically created for R+. So for now master is the correct branch.
But I will rebase it.

**Comment by Haxk20** [comment]
> Now that I think of it, even though this PR is well applicable to Q didn't we end up deciding to pull this in during the R release window?

Yes we did

**Comment by MarijnS95** [comment]
> Yes we did

Perhaps we should re-evaluate that. This change does not and should not break anything, but will create unnecessary divergence if we need backporting from R to Q or Q to R during early R bringup.

**Comment by Haxk20** [comment]
> > Yes we did
> 
> Perhaps we should re-evaluate that. This change does not and should not break anything, but will create unnecessary divergence if we need backporting from R to Q or Q to R during early R bringup.

Agreed

**Comment by Haxk20** [comment]
@pablomh @MarijnS95 Rebased ready for testing.

**Comment by pablomh** [comment]
Tested and nothing seems to be broken as a result.

**Comment by MarijnS95** [comment]
Yup, Seine behaves properly here too. If everything has been copied verbatim nothing should break (unless we have some sick overrides :stuck_out_tongue:).

**Pull request merged**
