### PR TITLE
[SEINE] Switch to CAF audio policy: take full advantage of the hardware

### PR DESCRIPTION
**Pull request by MarijnS95**
As with all other platforms, update `audio_platform_info` to the latest stock revision, including all new routes and updated sampling rates.

Tested on-device for quite a while with music playback, low latency sounds, voip calls. @Haxk20 you were daily-driving this patch, right?

@jerpelea Can you run this on your device for a day or two, include normal phone calls and validate everything keeps working smoothly?

### CODE REVIEW

**Comment by jerpelea** [comment]
I have it on my device

**Comment by Haxk20** [comment]
Included it on mine. Tho haven't run any tests yet. Will update after testing.

**Comment by Haxk20** [comment]
Breaks the bottom speaker in most cases. Right channel is routed to top earpiece and no output from bottom speaker.

And yes marijn even after rebooting

**Comment by jerpelea** [comment]
I will merge it as it is and we will fix the remaining bugs

**Pull request merged**
