### PR TITLE
Adjust acdb ids so echocancellation can work

### PR DESCRIPTION
**Pull request by AngryGami**
As requested by @ix5 creating pull request for the fix of https://github.com/sonyxperiadev/bug_tracker/issues/684

Signed-off-by: AngryGami <graymagi@gmail.com>

### CODE REVIEW

**Comment by MarijnS95** [comment]
Thanks!

I guess our mentoring session continues here. Especially when making obscure changes like these involving magic constants it is strongly preferred to write very elaborate commit messages:

- What broken behaviour is observed currently;
- Logs showcasing the routes, usecases and resulting ACDB IDs;
- What does stock do (also with logs, showing what ACDB IDs they pick for these usecases);
- How selecting a different ACDB ID solves a certain error or audible issue.

Look at similar files in other repos for inspiration.

In particular I don't think ACDB ID 14 - which is used for normal speaker audio playback - is tuned _at all_ for calls and simultaneous microphone use. And ACDB ID `11` seems to have fallen from the sky - I guess that is hardcoded in the HAL for some other usecase?

**Comment by MarijnS95** [comment]
Worth mentioning that we're not making this easy for you. Stock, as you might know, only uses the bottom speaker. But you have already come across `handset-as-speaker`, our "invention" to have stereo (well, it's currently mono over two speakers because routing is hard) in media playback and calls.

**Comment by AngryGami** [comment]
How I suppose to put logs into commit message?

**Comment by MarijnS95** [comment]
Cut them down to only the relevant lines (ie. those containing device+usecase+acdbid) and eventual errors, and indent them with _four_ spaces. See for example e4625e357f6154d066f60ea9bab2d8e99a283798.

**Comment by AngryGami** [comment]
> In particular I don't think ACDB ID 14 - which is used for normal speaker audio playback - is tuned at all for calls and simultaneous microphone use. And ACDB ID 11 seems to have fallen from the sky - I guess that is hardcoded in the HAL for some other usecase?

I don't understand this question... if you read [this](https://github.com/sonyxperiadev/bug_tracker/issues/684#issuecomment-809439050) you'll see that these values are what stock device prints in same situation, so I've just used them.

**Comment by MarijnS95** [comment]
That is what I'm asking to add to the commit, not link to some comment in some issue on some website.

Better question: why is Stock using `voice-speaker-mic` and OSS `voice-speaker-dmic-ef`? Chances are it's this:

https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-primary-hal/blob/1ee53035624ae1083f224d3b7a332368a856f08c/hal/msm8974/platform.c#L6554-L6558

But why is stock not having `SOURCE_DUAL_MIC`? Trace that back to `get_source_mic_type`, and find:

https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-primary-hal/blob/1ee53035624ae1083f224d3b7a332368a856f08c/hal/msm8974/platform.c#L2384

https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-primary-hal/blob/1ee53035624ae1083f224d3b7a332368a856f08c/hal/msm8974/platform.c#L7579-L7585


Has stock overridden mic count to 1? Or is your application not requesting stereo recording? I use https://gitlab.com/axet/android-audio-recorder in my testing to alternate between stereo and mono.

**Comment by AngryGami** [comment]
@MarijnS95 I don't understand you. Sorry.

**Comment by jerpelea** [comment]
cherry-picked

**Pull request closed without merging**
